INSERT INTO public."menuItems" VALUES (1, 'pizza', 'Small Thin Crust Pizza', 10, 'True');
INSERT INTO public."menuItems" VALUES (2, 'pizza', 'Medium Thin Crust Pizza', 12.5, 'True');
INSERT INTO public."menuItems" VALUES (3, 'pizza', 'Large Thin Crust Pizza', 15, 'True');
INSERT INTO public."menuItems" VALUES (4, 'pizza', 'Jumbo Thin Crust Pizza', 17.5, 'True');
INSERT INTO public."menuItems" VALUES (5, 'pizza', 'Small Deep Dish  Pizza', 14, 'True');
INSERT INTO public."menuItems" VALUES (6, 'pizza', 'Medium Deep Dish Pizza', 16, 'True');
INSERT INTO public."menuItems" VALUES (7, 'pizza', 'Large Deep Dish Pizza', 18, 'True');
INSERT INTO public."menuItems" VALUES (8, 'calzone', 'Calzone', 8, 'True');
INSERT INTO public."menuItems" VALUES (9, 'pizzaBread', 'Pizza Bread', 4, 'True');
INSERT INTO public."menuItems" VALUES (10, 'strudel', 'Strudel', 5, 'True');
INSERT INTO public."extraItems" VALUES (1, 'Sausage', 1);
INSERT INTO public."extraItems" VALUES (2, 'Pepperoni', 1);
INSERT INTO public."extraItems" VALUES (3, 'Meat Lovers', 2);
INSERT INTO public."extraItems" VALUES (4, 'Mushrooms', 0.5);
INSERT INTO public."extraItems" VALUES (5, 'Onions', 0.5);
INSERT INTO public."extraItems" VALUES (6, 'Green Peppers', 0.5);
INSERT INTO public."extraItems" VALUES (7, 'Veggie Delight', 1.5);
INSERT INTO public."extraItems" VALUES (8, 'Sausage Supreme', 3.5);
INSERT INTO public."extraItems" VALUES (9, 'Pepperoni Supreme', 3.5);
INSERT INTO public."extraItems" VALUES (10, 'The Works!', 4.5);
